baseURL = "/"
languageCode = "it-it"
title = "Paola Bovero"

disableKinds = ["taxonomy", "term"]

[params]
  description = "Sito ufficiale di Paola Bovero"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  
